version: 1

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm i
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
